apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "decreta.fullname" . }}
  labels:
    {{- include "decreta.labels" . | nindent 4 }}
data:
  NODE_ENV: {{ .Values.config.NODE_ENV | quote }}
  API_PORT: {{ .Values.config.API_PORT | quote }}
  POSTGRES_HOST: {{ include "decreta.postgresHost" . | quote }}
  POSTGRES_PORT: "5432"
  POSTGRES_USER: {{ .Values.postgres.user | quote }}
  POSTGRES_DB: {{ .Values.postgres.database | quote }}
  BOOTSTRAP_ADMIN_EMAIL: {{ .Values.config.BOOTSTRAP_ADMIN_EMAIL | quote }}
  BOOTSTRAP_ADMIN_NAME: {{ .Values.config.BOOTSTRAP_ADMIN_NAME | quote }}
